title: Events
url: syndication.streamdata.io
philosophy: This is our project area for tracking on conferences and other events that are relevant to Streamdata.io. We publish lists of the eveents we are watching, complete with their Twitter accounts, and searches for hashtags. Providing one place where we can find the events care about or will be attending.
events:
